export const residuos = [
  { nombre: "plastic bottle (pet)", puntos: 2 },
  { nombre: "paper", puntos: 20 },
  { nombre: "glass", puntos: 10 },
  { nombre: "can", puntos: 2 },
  { nombre: "aluminum can", puntos: 3 },
  { nombre: "battery", puntos: 20 },
  { nombre: "reusable bag", puntos: 5 },
  { nombre: "electronic equipment", puntos: 10 },
  { nombre: "plastic bag", puntos: 1 },
  { nombre: "cardboard", puntos: 25 },
  { nombre: "wood", puntos: 15 },
  { nombre: "scrap", puntos: 20 },
  { nombre: "wire", puntos: 5 },
  { nombre: "cell phone", puntos: 10 },
  { nombre: "tire", puntos: 4 },
];
