export const residuos = [
  { nombre: "botella de plástico (pet)", puntos: 2 },
  { nombre: "papel", puntos: 20 },
  { nombre: "vidrio", puntos: 10 },
  { nombre: "lata", puntos: 2 },
  { nombre: "lata de aluminio", puntos: 3 },
  { nombre: "batería", puntos: 20 },
  { nombre: "bolsa reutilizable", puntos: 5 },
  { nombre: "equipo electronico", puntos: 10 },
  { nombre: "bolsa de plastico", puntos: 1 },
  { nombre: "carton", puntos: 25 },
  { nombre: "madera", puntos: 15 },
  { nombre: "chatarra", puntos: 20 },
  { nombre: "cable", puntos: 5 },
  { nombre: "celular", puntos: 10 },
  { nombre: "llanta", puntos: 4 },
];
